"""
Django settings for SKW_ERP_SYSTEM project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# ProjectName
#       |__MainAppName(~ProjectName)
#                    |__settings.py
#
THIS_FILE_PATH = os.path.abspath(__file__)
MAIN_APP_DIR = os.path.dirname(THIS_FILE_PATH)
BASE_DIR = os.path.dirname(MAIN_APP_DIR)
PROJECT_DIR = BASE_DIR
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#print(THIS_FILE_PATH)
#print(MAIN_APP_DIR)
#print(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g1yr+iz!52#z0$zz$o3ed)i0d(8yg3ud9#@v=u(#24v56i_c16'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['172.30.3.140']


# Application definition

INSTALLED_APPS = [
    'accounts',
	'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
	'human_resource',
    'projects',	
	#'django.contrib.humanize',
	#'widget_tweaks',
	
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SKW_ERP_SYSTEM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SKW_ERP_SYSTEM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': 'skw_erp_system',
        'USER': 'admin_vn',
		'PASSWORD': 'skwadmin123',
		'HOST': 'localhost',
		'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Saigon'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'static'),
]

# login -> http://172.30.3.140:5555/ -> /home.html
# LOGIN_REDIRECT_URL: Tells Django which URL to redirect after login if the contrib.auth.views.login view gets no next parameter
LOGIN_REDIRECT_URL = 'home'

# login <-> http://172.30.3.140:5555/accounts/login/
# LOGIN_URL: Is the URL to redirect the user to log in (e.g. using the login_required decorator)
LOGIN_URL = 'login'

# login <-> http://172.30.3.140:5555/accounts/logout/
# LOGOUT_URL: Is the URL to redirect the user to log out
LOGOUT_URL = 'logout'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'